name: Techno Fattie
description: Josh Carroll's Blog about Programming, Techno and Fatties... ok mostly just programming.
base_url: http://localhost:4000
markdown: redcarpet
pygments: true
pygments_theme: vs
paginate: 5
paginate_path: "page:num"
safe: false
plugins: _plugins
gems: [jekyll/tagging,digest/md5,net/http]
tag_page_layout: tag_page
tag_page_dir: tags
archives_page_dir: archives
lsi: false