name: Techno Fattie
description: Josh Carroll's Blog about Programming, Techno and Fatties... ok mostly just programming.
url: http://www.technofattie.com
author: Josh Carroll
copyright: 2014 Josh Carroll All rights reserved
base_url: http://www.technofattie.com
markdown: redcarpet
pygments: true
pygments_theme: syntax
paginate: 5
paginate_path: "page:num"
safe: false
plugins: _plugins
gems: [jekyll/tagging,digest/md5,net/http]
tag_page_layout: tag_page
tag_page_dir: tags
archives_page_dir: archives
lsi: false
enable_analytics: false